kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "nodejs-demo"
  namespace: "nodejs-demo"
spec:
  runPolicy: "Serial"
  source:
    contextDir: "container"
    git:
      uri: "https://github.com/worsco/ocp-nodejs-demo"
      ref: "master"
  output:
    to:
      kind: ImageStreamTag
      name: "ocp-nodejs-demo:latest"
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: "ImageStreamTag"
        name: "ose-logging-fluentd:v4.3.22-202005201238"
        namespace: "openshift"
